modified files
Signed-off-by: R <aparnr@deloitte.com>

diff --git a/builds/apps/deploy-script.yaml b/builds/apps/deploy-script.yaml
--- a/builds/apps/deploy-script.yaml
+++ b/builds/apps/deploy-script.yaml
@@ -102,7 +102,12 @@ steps:
         # Apply Certificate
 
         echo "Applying Certificate..."
-        sed -i 's/{{_DOMAIN_}}/${_DOMAIN_}/g' deployments/configs/certificates.yaml
+        if sed -i -E "s|\{\{_DOMAIN_\}\}|${_DOMAIN_}|g" deployments/configs/certificates.yaml
+           echo "Successfully updated certificates.yaml
+        else
+            echo "Failed to update certificate.yaml"
+            exit 1
+        fi
         kubectl apply -f deployments/configs/certificates.yaml
         
         # Apply Gateway
