modified files
Signed-off-by: R <aparnr@deloitte.com>

diff --git a/builds/apps/deploy-script.yaml b/builds/apps/deploy-script.yaml
--- a/builds/apps/deploy-script.yaml
+++ b/builds/apps/deploy-script.yaml
@@ -73,20 +73,18 @@ steps:
 
 
         # Update the mapper-api DB_HOSTNAME in values.yaml
-        # sed -i "s|SPAR_MAPPER_DB_HOSTNAME: ''|SPAR_MAPPER_DB_HOSTNAME: '$sqlIP'|" -f deployments/configs/values.yaml
         sed -i "s|SPAR_MAPPER_DB_HOSTNAME: ''|SPAR_MAPPER_DB_HOSTNAME: '$sqlIP'|" deployments/configs/values.yaml
         cat deployments/configs/values.yaml | grep SPAR_MAPPER_DB_HOSTNAME
 
 
         # Update the spar-self-service-api DB_HOSTNAME in values.yaml
         echo "Updating SPAR_SELFSERVICE_DB_HOSTNAME in values.yaml..."
-        sed -i "s|SPAR_SELFSERVICE_DB_HOSTNAME: ''|SPAR_SELFSERVICE_DB_HOSTNAME: '$sqlIP'|" deployments/configs/values.yaml
-        #sed -i "s|\(SPAR_SELFSERVICE_DB_HOSTNAME: \).*|\1'$sqlIP'|" deployments/configs/values.yaml        
+
+        sed -i "s|SPAR_SELFSERVICE_DB_HOSTNAME: ''|SPAR_SELFSERVICE_DB_HOSTNAME: '$sqlIP'|" deployments/configs/values.yaml             
         cat deployments/configs/values.yaml | grep SPAR_SELFSERVICE_DB_HOSTNAME
 
         # Replace the domain placeholder in gateway.yaml
-        echo "Updating gateway.yaml with the domain..."
-        sed -i "s/{{_DOMAIN_}}/${_DOMAIN_}/g" deployments/configs/certificates.yaml
+        sed -i "s/{{_DOMAIN_}}/${_DOMAIN_}/g" deployments/configs/gateway.yaml
 
         # Install SPAR
         echo "Installing SPAR with Helm..."
@@ -104,11 +102,17 @@ steps:
         # Apply Certificate
 
         echo "Applying Certificate..."
-        sed -i "s/{{_DOMAIN_}}/${_DOMAIN_}/g" deployments/configs/certificates.yaml
+        sed -i 's/{{_DOMAIN_}}/${_DOMAIN_}/g' deployments/configs/certificates.yaml
         kubectl apply -f deployments/configs/certificates.yaml
         
         # Apply Gateway
         echo "Applying Gateway..."
+        if sed -i -E "s|{{_DOMAIN_}}|${_DOMAIN_}|g" deployments/configs/gateway.yaml; then
+            echo "Successfully updated gateway.yaml"
+        else
+            echo "Failed to update gateway.yaml"
+            exit 1
+        fi
         kubectl apply -f deployments/configs/gateway.yaml
 
 tags: ['cloud-builders-community']
