modified files
Signed-off-by: R <aparnr@deloitte.com>

diff --git a/builds/apps/deploy-script.yaml b/builds/apps/deploy-script.yaml
--- a/builds/apps/deploy-script.yaml
+++ b/builds/apps/deploy-script.yaml
@@ -120,6 +120,15 @@ steps:
         fi
         kubectl apply -f deployments/configs/gateway.yaml
 
+        # Apply virtualservice 
+        if sed -i -E "s|\{\{_DOMAIN_\}\}|${_DOMAIN_}|g" deployments/configs/virtualservice.yaml; then
+            echo "Successfully updated virtualservice.yaml"
+        else
+            echo "Failed to update virtualservice.yaml"
+            exit 1
+        fi
+        kubectl apply -f deployments/configs/virtualservice.yaml
+
 tags: ['cloud-builders-community']
 serviceAccount: "projects/${_PROJECT_ID_}/serviceAccounts/${_SERVICE_ACCOUNT_}"
 logsBucket: "gs://${_LOG_BUCKET_}"
